#!/usr/bin/env python3
"""dev_deps_doctor — one-screen diagnosis of the local-dependency layer.

Cross-checks three sources of truth that this workspace has repeatedly let drift
(urirun_flow, urirun_connector_router and urirun_scanner all diverged silently):

1. LIVE import resolution — where does each import name actually load from?
2. Editable-finder mappings in the venv — which distribution claims each name?
3. ``local.dev.txt`` (generated by ~/github/local.dev.sh) — declared local deps
   and their install status (STALE-INSTALL / NON-EDITABLE fixes).

Verdicts per import name:
- SHADOW      — the name loads from a directory that a DIFFERENT distribution owns
                (the urirun_flow disease: sys.path beats editable finders).
- DEAD-SHELL  — a sibling repo claims the name (dist installed from it) but has no
                package sources; the code actually lives elsewhere.
- NO-GIT      — the owning local source directory is not a git repository.
- OK          — resolution, ownership and sources agree.

Exit code 1 when any SHADOW is found (CI-fail worthy); other findings are advisory.
Run:  python scripts/dev_deps_doctor.py
"""
from __future__ import annotations

import glob
import importlib.util
import json
import os
import re
import sys
from pathlib import Path

_ADAPTERS = Path(__file__).resolve().parents[1]


def _site_packages() -> Path | None:
    for p in sys.path:
        if p.endswith("site-packages") and Path(p).is_dir():
            return Path(p)
    return None


def editable_owners(site: Path) -> dict[str, Path]:
    """import name -> package dir, from every __editable__ finder MAPPING in the venv."""
    owners: dict[str, Path] = {}
    for f in sorted(glob.glob(str(site / "__editable__*_finder.py"))):
        text = Path(f).read_text(encoding="utf-8", errors="replace")
        m = re.search(r"MAPPING[^=]*=\s*\{([^}]*)\}", text)
        if not m:
            continue
        for pkg, path in re.findall(r"'([\w.]+)':\s*'([^']+)'", m.group(1)):
            owners[pkg] = Path(path)
    return owners


def dist_owners(site: Path) -> dict[str, Path]:
    """import name -> source repo, for non-editable local installs (direct_url file://)."""
    owners: dict[str, Path] = {}
    for du in glob.glob(str(site / "*.dist-info" / "direct_url.json")):
        try:
            url = json.loads(Path(du).read_text()).get("url") or ""
        except Exception:  # noqa: BLE001
            continue
        if not url.startswith("file://"):
            continue
        top = Path(du).parent / "top_level.txt"
        names = top.read_text().split() if top.exists() else []
        for name in names:
            owners.setdefault(name, Path(url[len("file://"):]))
    return owners


def _dist_meta(dist_info: Path) -> tuple[str, str]:
    """(distribution name, installed version) from a dist-info METADATA file."""
    name = version = ""
    try:
        for line in (dist_info / "METADATA").read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("Name: "):
                name = line[6:].strip()
            elif line.startswith("Version: "):
                version = line[9:].strip()
            elif not line.strip():
                break
    except Exception:  # noqa: BLE001
        pass
    return name, version


def _source_version(repo: Path) -> str:
    """Declared version at the local source (pyproject [project].version or VERSION file)."""
    pyproject = repo / "pyproject.toml"
    if pyproject.exists():
        m = re.search(r'^version\s*=\s*"([^"]+)"', pyproject.read_text(encoding="utf-8", errors="replace"), re.M)
        if m:
            return m.group(1)
    version_file = repo / "VERSION"
    if version_file.exists():
        return version_file.read_text().strip()
    return ""


def _version_key(v: str) -> tuple:
    return tuple(int(p) if p.isdigit() else 0 for p in re.split(r"[.+-]", v or "0"))


def local_install_health(site: Path) -> list[dict]:
    """LIVE stale-check of every local file:// install — no reliance on generated manifests
    (they go stale themselves; a local.dev.txt from the morning already lied by noon).

    Editable installs cannot be version-stale (the code IS the source); non-editable
    local installs are compared against the source's declared version."""
    findings: list[dict] = []
    for du in sorted(glob.glob(str(site / "*.dist-info" / "direct_url.json"))):
        dist_info = Path(du).parent
        try:
            info = json.loads(Path(du).read_text())
        except Exception:  # noqa: BLE001
            continue
        url = info.get("url") or ""
        if not url.startswith("file://"):
            continue
        editable = bool((info.get("dir_info") or {}).get("editable"))
        if editable:
            continue
        repo = Path(url[len("file://"):])
        name, installed = _dist_meta(dist_info)
        src_version = _source_version(repo)
        verdict = "NON-EDITABLE"
        if src_version and _version_key(src_version) > _version_key(installed):
            verdict = f"STALE-INSTALL (installed {installed}, source {src_version})"
        findings.append({"name": name, "installed": installed, "source": str(repo),
                         "sourceVersion": src_version, "verdict": verdict,
                         "fix": f"pip install -e {repo}"})
    return findings


def resolve(name: str) -> Path | None:
    try:
        spec = importlib.util.find_spec(name)
    except Exception:  # noqa: BLE001
        return None
    if spec and spec.origin and spec.origin != "namespace":
        return Path(spec.origin).parent
    return None


def local_dev_statuses(project_dir: Path) -> list[str]:
    """The STALE-INSTALL / NON-EDITABLE fix lines from this project's local.dev.txt."""
    manifest = project_dir / "local.dev.txt"
    if not manifest.exists():
        return []
    return [line.strip() for line in manifest.read_text(encoding="utf-8").splitlines()
            if "-> fix:" in line]


def _has_sources(pkg_dir: Path) -> bool:
    return pkg_dir.is_dir() and any(pkg_dir.rglob("*.py"))


def _pkg_dir_in_repo(repo: Path, name: str) -> Path:
    """Package dir inside a source repo, honoring both flat and src/ layouts."""
    for candidate in (repo / name, repo / "src" / name):
        if candidate.is_dir():
            return candidate
    return repo / name


def _under_git(path: Path) -> bool:
    """True when ``path`` sits inside a git work tree (walks up to $HOME)."""
    home = Path.home()
    cur = path if path.is_dir() else path.parent
    while str(cur).startswith(str(home)) and cur != home:
        if (cur / ".git").exists():
            return True
        cur = cur.parent
    return False


def diagnose() -> int:
    site = _site_packages()
    if site is None:
        print("no site-packages on sys.path — run inside the project venv")
        return 2
    owners = editable_owners(site)
    dists = dist_owners(site)
    shadows: list[str] = []
    rows: list[tuple[str, str, str]] = []
    names = sorted(set(owners) | set(dists))
    for name in names:
        owner = owners.get(name) or _pkg_dir_in_repo(dists.get(name, Path()), name)
        resolved = resolve(name)
        verdicts = []
        if resolved is None:
            verdicts.append("UNIMPORTABLE")
        elif owner and resolved.resolve() != owner.resolve():
            verdicts.append(f"SHADOW → loads {resolved}")
            shadows.append(name)
        src_repo = (owners.get(name) or dists.get(name))
        if src_repo is not None:
            if not _has_sources(owners.get(name) or _pkg_dir_in_repo(dists[name], name)):
                verdicts.append("DEAD-SHELL (no package sources at owner)")
            if not _under_git(src_repo) and str(src_repo).startswith(str(Path.home())):
                verdicts.append("NO-GIT")
        rows.append((name, str(owner), "; ".join(verdicts) or "OK"))
    width = max(len(r[0]) for r in rows) if rows else 0
    for name, owner, verdict in rows:
        mark = "!!" if verdict != "OK" else "  "
        print(f"{mark} {name:{width}s}  {verdict}")
    health = local_install_health(site)
    stale = [h for h in health if h["verdict"].startswith("STALE")]
    if health:
        print("\nlocal file:// installs (non-editable):")
        for h in health:
            print(f"  {h['name']} {h['installed']}  ← {h['source']}  {h['verdict']}")
    fixes = local_dev_statuses(_ADAPTERS)
    if fixes:
        print("\nlocal.dev.txt pending fixes (manifest may itself be stale — trust the live section above):")
        for line in fixes:
            print("  " + line)
    if shadows:
        print(f"\nFAIL: {len(shadows)} shadowed import name(s): {', '.join(shadows)}")
        return 1
    if stale:
        print(f"\nFAIL: {len(stale)} stale local install(s) — run with --fix to reinstall editable")
        return 1
    return 0


def apply_fixes() -> int:
    """Reinstall every stale non-editable local install as editable (pip install -e)."""
    import subprocess  # noqa: PLC0415
    site = _site_packages()
    if site is None:
        return 2
    stale = [h for h in local_install_health(site) if h["verdict"].startswith("STALE")]
    if not stale:
        print("nothing stale — no fixes to apply")
        return 0
    for h in stale:
        print(f"fixing {h['name']}: {h['fix']}")
        subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-e", h["source"]], check=True)
    return diagnose()


if __name__ == "__main__":
    raise SystemExit(apply_fixes() if "--fix" in sys.argv else diagnose())
