flowchart TD
%% generated in 0.01s
    adapters__js["adapters.js<br/>12 funcs"]
    adapters__python["adapters.python<br/>382 funcs"]
    v1__examples["v1.examples<br/>54 funcs"]
    adapters__python ==>|6| v1__examples
    adapters__python ==>|4| adapters__js
