services:
  user-service:
    image: example/user-service
    labels:
      - "urihandler.enabled=true"
      - "urihandler.uri=service://api/user/create/basic"
      - "urihandler.kind=http"
      - "urihandler.adapter=fetch"
      - "urihandler.method=POST"
      - "urihandler.url=http://user-service:8080/api/users"
